Vagrant.configure("2") do |config|
  config.vm.box = "peru/ubuntu-18.04-desktop-amd64"
  config.vm.box_version = "20190901.01"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provision "shell", run: "always", inline: <<-SHELL
      apt-get update
      apt-get install -y\
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common
      
      # ansible
      apt-add-repository ppa:ansible/ansible
      
      # sublime 3
      wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
      echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list

      # apt-get update
      apt-get install -y git
      apt-get install -y ansible
      apt-get install -y sublime-text
      apt-get install -y python3-pip

      # virtualenv
      pip3 install virtualenv
      pip3 install virtualenvwrapper
      echo "export HOME=/home/vagrant/" >> /home/vagrant/.bashrc
      echo "export WORKON_HOME=/home/vagrant//.virtualenvs" >> /home/vagrant/.bashrc
      echo "export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3" >> /home/vagrant/.bashrc
      echo "export VIRTUALENVWRAPPER_VIRTUALENV=/usr/local/bin/virtualenv" >> /home/vagrant/.bashrc
      echo "source /usr/local/bin/virtualenvwrapper.sh" >> /home/vagrant/.bashrc

      # awscli
      pip3 install --upgrade --user awscli
      echo "export PATH=/home/ec2-user/.local/bin:$PATH" >> /home/vagrant/.bashrc
      aws --version

      # chrome
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo dpkg -i google-chrome-stable_current_amd64.deb

      # zsh
      # apt-get install -y zsh
      # chsh -s /usr/bin/zsh vagrant

      # oh-my-zsh
      # wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh | q

      # cp /home/vagrant/.oh-my-zsh/templates/zshrc.zsh-template /home/vagrant/.zshrc
      # source /home/vagrant/.zshrc


    SHELL
    
end