version: '3'
services:
  console-helloworld:
    build: ../docker/1.console-helloworld
  web-nginx:
    build: ../docker/2.web-nginx
    ports:
    - "8080:80"
  web-python-flask:
    build: ../docker/3.web-python-flask
    ports:
    - "80:80"
  console-dependency:
    build: ../docker/4.console-dependency
    links:
    - web-python-flask:citymatcher
    depends_on:
    - web-python-flask
